### ISSUE TITLE
touch results

### ISSUE THREAD

**Issue by jinshihui** [KingWalrus/SweepingCapSense#1]
Hi, what is this mean(in the example file):
touch.setResults(i, touch.getResults(i)_0.5+(float)(touch.getValue()_0.5));

**Comment by chonigman** [comment]
Hi. 

This line is simply setting the results at frequency "i" - the math is a simple low pass filter to help smooth out the data. It is not required, you could just use:
touch.setResults(i, touch.getValue());

**Comment by KingWalrus** [comment]
- [
